# Introduction to Machine Learning

1. Judge input value 
2. convert the data into numpy array (Numbers)
3. encoding -> convert string type of data into numerical
4. train -> part ML model -> patterns -> 70% or 80% of data 
5. test -> cross verify -> what machine learn is correct or not -> 30% or 20% of data is to be test
6. x_train -> input 
   y_train -> output
   x_test -> independent values
   y_test -> dependent values 
7. y_pred -> prediction on x_test input 
8. y_test == y_pred -> model work correctly

How ML Models Works ??

1. input -> x_train, y_train 
2. gives logic 
3. logic input -> x_test
         output -> y_pred 

Types of ML models

1. supervised -> labelled data (servey - discrete vlaue) 
    A. classification (categorical)
    B. regression (random variable)
2. unsupervised -> unlabelled data (cluster)
3. reinforcement -> changing data

### separation of dataset for ML Model
![My Image](separation_of_dataset.png)

### working of ML model
![My Image](working_of_ML.png)

# KNN (K Nearest Neighbour)

1. No. of nearest neighbours to include in the majority of voting process
2. white wine glass go to group red wine 

Steps:

1. find distance
2. find nearest one
3. choose majority 

K = even 
choose only odd value 

Identification of value K 

k = sqrt(N)
where, N is Number of sample in your training dataset

Types Algorithm to fine value of k in KNN:

1. Eucledian 
$$
d = \sqrt{(x_1 - x_2)^2 + (y_1 - y_2)^2}
$$

2. Manhattan
$$
d = |x_1 - x_2| + |y_1 - y_2|
$$

### Example of KNN
![My Image](KNN_example.png)

Eucledian Formula for k
$$
d = \sqrt{\sum_{i=1}^{k} (x_i - y_i)^2}
$$

### Example of KNN By Eucledian Formula

![My Image](KNN_ex_1.png)
![My Image](KNN_ex_2.png)

Prons:
1. flexible to feature/distance choices
2. natuarally handeles multi-class cases
3. can do well in practice with representative data

Cons:
1. need to ddetermine the value of parameter K (number of nearest neighbours)
2. computation cost is high
3. storage of data

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Siddhi\Desktop\Data Science\Dataset\Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [6]:
# Input : Age, EstimatedSalary
# Output : Purchased

x = df.iloc[:,2:4]
y = df.iloc[:,[-1]]
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [7]:
y

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [10]:
# split the dataset into train-test-split

from sklearn.model_selection import train_test_split # for spliting the data

# dont shuffle the position
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 4)

In [11]:
x_train.shape

(280, 2)

In [12]:
y_test.shape

(120, 1)

In [15]:
x_train # random_state -> random selecttion of rows

     Age  EstimatedSalary
33    28            44000
195   34            43000
286   37            62000
221   35            91000
239   53           143000
..   ...              ...
360   43           129000
385   56            60000
197   20            36000
174   34            72000
122   40            75000

[280 rows x 2 columns]

In [14]:
y_test

     Purchased
184          0
6            0
61           0
312          0
100          0
..         ...
334          1
188          0
245          1
301          1
93           0

[120 rows x 1 columns]

In [17]:
from sklearn.neighbors import KNeighborsClassifier

Knn = KNeighborsClassifier(n_neighbors = 17)
Knn.fit(x_train, y_train)
y_pred = Knn.predict(x_test)

C:\Users\Siddhi\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [20]:
y_pred, y_test

(array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 0]),
      Purchased
 184          0
 6            0
 61           0
 312          0
 100          0
 ..         ...
 334          1
 188          0
 245          1
 301          1
 93           0

 [120 rows x 1 columns])

In [21]:
y_test.head(10)

     Purchased
184          0
6            0
61           0
312          0
100          0
274          1
367          1
320          1
291          1
330          0

# Confusion Matrix

![My Image](confusion_matrix.png)

In [22]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[77  4]
 [15 24]]

In [29]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
print(accuracy_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))

# Error-rate
print(1-accuracy_score(y_test,y_pred))

0.8416666666666667
0.8571428571428571
0.6153846153846154
0.15833333333333333